version: '3'
services:
  ocelot:
    build: ./Ocelot.Gateway
    ports:
      - 9090:8080
    networks:
      - ocelot-net

  weather-service:
    container_name: service
    build: ../service/Service.API
    networks:
      - ocelot-net
    ports:
      - "8080:8080"

networks:
  ocelot-net:
    external: false