version: '3'
services:
  yarp:
    build: ./Yarp.Gateway
    ports:
      - 9090:8080
    networks:
      - yarp-net

  weather-service:
    container_name: service
    build: ../service/Service.API
    networks:
      - yarp-net
    ports:
      - "8080:8080"

networks:
  yarp-net:
    external: false